### PR TITLE
Simplify HAR Facing Logic

### LINKED ISSUE #342: Chronos faces wrong way after teleport

### PR DESCRIPTION
**Pull request by LegendaryBlueShirt**
fixes #342

### CODE REVIEW

File: src/game/scenes/arena.c [hunk 1]
```diff
@@ -785,12 +775,6 @@ void arena_har_hook(har_event event, void *data) {
             }
             break;
         case HAR_EVENT_LAND:
-            if(har2->state == STATE_STANDING || har_is_crouching(har2) || har_is_walking(har2) ||
-               har2->executing_move) {
-                // if the other HAR is jumping or recoiling, don't flip the direction. This specifically is to fix
-                // jaguar ending up facing backwards after an overhead throw.
-                arena_maybe_turn_har(other_player_id, scene);
```
Comment (Vagabond) [inline src/game/scenes/arena.c:792]: looks like you can remove arena_maybe_turn_har entirely now? :tada:

Comment (LegendaryBlueShirt) [reply src/game/scenes/arena.c:792]: I think I will.

**Review by Vagabond — APPROVED** [review]
