### PR TITLE
Fix 2 movement bugs:

### LINKED ISSUE #814: Reduced walkspeed after bumping enemy
After walking into an opponent, ones HAR cannot walk backwards as fast as it normally can.

Attached video starts by showing that this does not happen in DOS, and then switches to OpenOMF to show the bug.

https://github.com/user-attachments/assets/2747c5ff-6923-4171-9034-42a4a2476fbb

### PR DESCRIPTION
**Pull request by Vagabond**
* Fixes #814 When walking away from a HAR, restore normal walking speed
* Pushback from a move decreases over time if you're touching the ground. This is commonly seen when you do like a roundhouse while the enemy is up against the wall, you'll be pushed back for the duration of the attack animation.

### CODE REVIEW

File: src/game/objects/har.c [hunk 1]
```diff
@@ -590,6 +590,24 @@ void har_move(object *obj) {
                     har_finished(obj);
                 }
             }
+        } else if(h->state != STATE_WALKFROM && h->state != STATE_WALKTO) {
+            // add some friction from the floor if we're not walking
+            // This is important to dampen/eliminate the velocity added from pushing away from the other HAR
+            if(vel.x > 0.0f) {
+                if(vel.x - 0.2f > 0.0f) {
```
Comment (katajakasa) [inline src/game/objects/har.c:597]: This could be an edge function btw ;)

**Review by katajakasa — APPROVED** [review]

File: src/game/objects/har.c (hunk 1 above)
Comment (Vagabond) [reply src/game/objects/har.c:597]: what is that?

Comment (katajakasa) [reply src/game/objects/har.c:597]: Sorry, step function. Brain fart. E.g. https://thebookofshaders.com/glossary/?search=step
