### PR TITLE
Various Mechlab/Tournament UI Fixes

### LINKED ISSUE #1106: [GAMEPLAY] Running out of money on tournament leads to a forever disabled pilot
**Steps to reproduce**
What happened?
I lost too much money in tournament, Plug warned me that I had one final chance to win, but failed that, and then I got kicked out of the tournament and my money was set to $0 K. With this pilot, the only choices I have is to load another pilot or create a new one.

What did you expect to happen?
I expected there to be some way to recover from this financial hardship I entered, and continue with this pilot into another tournament.

Version was v0.8.0.

Image

### PR DESCRIPTION
**Pull request by Nopey**
Fixes #1106

### CODE REVIEW

**Review by katajakasa — APPROVED** [review]
Tested, works, code seems fine. LGTM.

File: src/game/scenes/mechlab/lab_menu_main.c [hunk 1]
```diff
@@ -252,7 +266,7 @@ static const spritebutton_tick_cb tick_cbs[] = {
     lab_menu_tick_in_tournament, // lab_menu_tick_delete,
     lab_menu_tick_in_tournament, // lab_menu_tick_sim,
     NULL,                        // lab_menu_tick_quit,
-    lab_menu_tick_in_tournament, // lab_menu_tick_tournament,
```
Comment (Vagabond) [inline src/game/scenes/mechlab/lab_menu_main.c:255]: This should be disabled when there's not a player loaded, at least.

Comment (Nopey) [reply src/game/scenes/mechlab/lab_menu_main.c:255]: The loop in lab_menu_main_create handles it.

that loop now also now sets supports_select, so the buttons the loop disables can't be selected.

**Comment by Vagabond** [comment]
Erasing the "last" pilot name from my openomf config, booting the game and then loading a character gives me a greyed out new tournament button.

**Comment by Vagabond** [comment]
Leaving and re-entering tournament mode seems to fix it.

**Comment by Vagabond** [comment]
I set my money to 0 on a fresh character, and lost to cosette twice. I got kicked out of the tournment and was able to rejoin with 0 credits (my credits were negative before). I don't remember what's supposed to happen, though.

File: src/resources/trnmanager.c [hunk 2]
```diff
@@ -9,6 +9,12 @@
 #include <stdio.h>
 #include <string.h>
 
+static int trn_sort_compare_fn(const void *a, const void *b) {
+    sd_tournament_file const *trn_a = a;
+    sd_tournament_file const *trn_b = b;
+    return (trn_a->registration_fee > trn_b->registration_fee) - (trn_a->registration_fee < trn_b->registration_fee);
```
Comment (mrannanj) [inline src/resources/trnmanager.c:15]: What's the problem with just `return trn_a->registration_fee - trn_b->registration_fee;` here?

Comment (Nopey) [reply src/resources/trnmanager.c:15]: i don't want to overflow or underflow an integer.

**Comment by Nopey** [comment]
> I set my money to 0 on a fresh character, and lost to cosette twice. I got kicked out of the tournment and was able to rejoin with 0 credits (my credits were negative before). I don't remember what's supposed to happen, though.

We're missing the "you have to work as a mechanic" and "while working as a mechanic your HAR upgrades / training courses rotted" behaviors.

The credits going negative (after the warning) and then zero (after being kicked out) is correct.

**Comment by Nopey** [comment]
pushed more fixes:
- rewrote hardcoded tournament filename behaviors (the original four tournaments are not special-cased, and are not even referenced anywhere in MASTER.DAT).
- `scene` cheat now works with scene names (previously, the strings would never have matching case)
- implemented tournament cutscene replay cheat 'e'

File: src/formats/chr.h [hunk 3]
```diff
@@ -40,7 +40,7 @@ typedef struct {
     sd_sprite *photo;                       ///< Pilot photo
     float winnings_multiplier;              ///< Tournament winnings multiplier
     sd_chr_enemy *enemies[MAX_CHR_ENEMIES]; ///< List of enemy states in current tournament
-    unsigned int cutscene;                  ///< cutscene id for end of tournament
+    char bk_name[14];                       //< cutscene bk for end of tournament
```
Comment (mrannanj) [inline src/formats/chr.h:43]: Well, guess use 3 slashes on all since the others have it too

**Review by mrannanj — CHANGES_REQUESTED** [review]

File: src/formats/chr.h (hunk 3 above)
Comment (katajakasa) [reply src/formats/chr.h]: It's doxygen syntax. Reminds me, it has probably been a while since anyone has printed the game docs :/

File: src/formats/chr.h [hunk 4]
```diff
@@ -40,7 +40,8 @@ typedef struct {
     sd_sprite *photo;                       ///< Pilot photo
     float winnings_multiplier;              ///< Tournament winnings multiplier
     sd_chr_enemy *enemies[MAX_CHR_ENEMIES]; ///< List of enemy states in current tournament
-    unsigned int cutscene;                  ///< cutscene id for end of tournament
+    char bk_name[14];                       ///< cutscene bk for end of tournament
+    int tournament_id;                      ///< misnomer? set to 4 for WORLD.BK cutscene quirks
```
Comment (Vagabond) [inline src/formats/chr.h:44]: It does correspond to TOURNAMENT_NUMBER in the tournament compiler LST files.

Comment (Nopey) [reply src/formats/chr.h:44]: Ah, thanks. I did a search for "TOURNAMENT_ID" and came up blank :P
will remove the misnomer comment.

File: src/resources/trnmanager.c [hunk 5]
```diff
@@ -3,26 +3,29 @@
...
 #include <stdio.h>
 #include <string.h>
 
-static void trnlist_node_free_callback(void *data) {
-    sd_tournament_file *trn = data;
-    sd_tournament_free(trn);
+static int trn_sort_compare_fn(const void *a, const void *b) {
+    sd_tournament_file const *trn_a = a;
+    sd_tournament_file const *trn_b = b;
+    return (trn_a->registration_fee > trn_b->registration_fee) - (trn_a->registration_fee < trn_b->registration_fee);
```
Comment (Vagabond) [inline src/resources/trnmanager.c:15]: I *believe* the original game sorts by the ID first and then by the fee, if there's more than 1 with the same ID? See https://omf2097.com/wiki/doku.php?id=omf2097:robyrt_tourn

Comment (Nopey) [reply src/resources/trnmanager.c:15]: thanks, i'll do a quick n' dirty TRN file edit to verify and then use the correct logic.

**Review by Vagabond — APPROVED** [review]

File: src/resources/trnmanager.c (hunk 5 above)
Comment (Nopey) [reply src/resources/trnmanager.c:15]: the linked wiki is wrong. tournaments are not sorted by `TOURNAMENT NUMBER`.

Comment (Vagabond) [reply src/resources/trnmanager.c:15]: Good to know.

**Review by mrannanj — APPROVED** [review]
