### PR TITLE
Fixed Fire Pit Orb

### LINKED ISSUE #1163: [GAMEPLAY] Fire Pit Orb not hittable
**Steps to reproduce**
- Try to hit the fire pit orb
- Nothing will happen

With the recent change to make Pyros's flames not hittable, any hit detection involving palette indices not in HAR range stopped working.  May need to check whether the object being hit is a fire pit orb or not

### PR DESCRIPTION
**Pull request by LegendaryBlueShirt**
- Orb movement is now source accurate
- fixes #1163 
- Removed bespoke orbit logic

### CODE REVIEW

File: src/game/protos/player.c [hunk 1]
```diff
@@ -653,6 +647,28 @@ void player_run(object *obj) {
         }
     }
 
+    // Orb meandering.  Only the fire pit orb should have this tag set.
+    if(sd_script_isset(frame, "as")) {
+        double t = sinf(((obj->orb_val & 7) + 8.f) * ((abs(obj->orb_val * 4) + obj->gs->tick) * 0.003574533) +
```
Comment (katajakasa) [inline src/game/protos/player.c:652]: formatter really mangles this -- could you split these into a couple of lines with a helper variable or something ? Would be easier to read.

Comment (katajakasa) [reply src/game/protos/player.c:652]: Where do the magic values come from, btw ?

Comment (LegendaryBlueShirt) [reply src/game/protos/player.c:652]: I wouldn't be surprised if there's some mathematics book somewhere in Rob's attic with this curve formula.

Comment (LegendaryBlueShirt) [reply src/game/protos/player.c:652]: https://github.com/omf2097/omfsrc/blob/d3e60c230fd9c7e4902cadfc3735f4d1b396c9fa/backdrop.cpp#L880

**Review by katajakasa — APPROVED** [review]
I see more red then green, I like.

Squash!
