### PR TITLE
Fix Stunning After Throws

### LINKED ISSUE #1207: [GAMEPLAY] Throws Cannot Stun
**Steps to reproduce**
Try using Jaguar regular throw over and over again in netplay, the opponent will never get stunned

[20250418_095453.zip](https://github.com/user-attachments/files/19814522/20250418_095453.zip)

**Platform (please complete the following information):**
 - OS: Windows
 - Version adt/netcode-hacking

### PR DESCRIPTION
**Pull request by LegendaryBlueShirt**
fixes #1207

### CODE REVIEW

File: src/game/objects/har.c [hunk 1]
```diff
@@ -726,6 +726,28 @@ void har_move(object *obj) {
...
+    har *h = object_get_userdata(obj);
+
+    if(h->state == STATE_RECOIL && object_is_airborne(obj)) { // Less stun on rehit and throws
+        stun_amount /= 2;
+    }
+    stun_amount = (stun_amount * 2 + 12) * 256;
+    log_debug("applying %f stun damage to %f", stun_amount, h->endurance);
+    h->endurance += stun_amount;
+
+    if(h->endurance < 1.0f) {
```
Comment (Vagabond) [inline src/game/objects/har.c:739]: It's not a float anymore, right?

Comment (LegendaryBlueShirt) [reply src/game/objects/har.c:739]: You're right!

**Review by Vagabond — APPROVED** [review]
